# =========================================================
# Config / inputs
# =========================================================

WAILS_JSON := wails.json
APPLE_TEAM_ID := 98PKWYG94J
NOTARY_PROFILE := AC_PROFILE

empty :=
space := $(empty) $(empty)

# =========================================================
# Metadata derived from wails.json
# =========================================================

BINARY_NAME := $(shell jq -r '.outputfilename' $(WAILS_JSON))
VERSION := $(shell jq -r '.info.productVersion' $(WAILS_JSON))
PRODUCT_NAME := $(shell jq -r '.info.productName' $(WAILS_JSON))
AUTHOR_NAME := $(shell jq -r '.author.name' $(WAILS_JSON))

PRODUCT_SLUG := $(subst $(space),-,$(PRODUCT_NAME))

VOL_NAME := $(PRODUCT_NAME)
APP_NAME := $(PRODUCT_NAME).app
DMG_NAME := $(PRODUCT_SLUG)-v$(VERSION).dmg

# =========================================================
# Build artifact paths
# =========================================================

# Root build directory and subdirectory where final build artifacts are placed.
BUILD_DIR := build
BIN_DIR := $(BUILD_DIR)/bin

# Path to the packaged Wails .app bundle generated by `wails build`.
APP_SOURCE := $(BIN_DIR)/$(BINARY_NAME).app

# Path to the actual executable binary inside the .app bundle.
APP_EXEC := $(APP_SOURCE)/Contents/MacOS/$(BINARY_NAME)

# Temporary staging directory used to assemble DMG contents before packaging.
DMG_DIR := $(BUILD_DIR)/dmg

# Final DMG filename and full path to the installer artifact.
DMG_PATH := $(BIN_DIR)/$(DMG_NAME)

# =========================================================
# Build options / platform detection
# =========================================================

# Wails/Go release build flags:
# -s -w     strip symbol/debug info to reduce binary size
# -trimpath removes local filesystem paths from the compiled binary
WAILS_BUILD_FLAGS := -ldflags "-s -w" -trimpath

# Capture host OS and architecture so the build can branch by platform.
UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)

# =========================================================
# Apple signing / notarization config
# =========================================================

# Exact Developer ID Application certificate name used by codesign.
APPLE_SIGN_IDENTITY := Developer ID Application: $(AUTHOR_NAME) ($(APPLE_TEAM_ID))

# =========================================================
# Terminal formatting
# =========================================================

BOLD := \033[1m
RESET := \033[0m
RED := \033[1;31m
GREEN := \033[1;32m
YELLOW := \033[1;33m
HEADER := \033[1;34m

# =========================================================
# Phony targets
# =========================================================

.PHONY: \
	help \
	all \
	check \
	check-wails \
	build \
	sign-app \
	verify-sign \
	stage-dmg \
	stage-dmg-unsigned \
	dmg \
	dmg-unsigned \
	sign-dmg \
	notarize-dmg \
	staple-dmg \
	verify-notarization \
	release \
	local-release \
	test \
	run \
	clean \
	start-section

# =========================================================
# Top-level targets
# =========================================================

.DEFAULT_GOAL := help

help: ## Show available make targets
	@echo ""
	@echo "Available targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

all: build ## Build the application

local-release: clean build dmg-unsigned ## Build and package an unsigned DMG for local testing

# Full release pipeline:
# 1. clean old build artifacts
# 2. build the app
# 3. sign the .app bundle
# 4. stage DMG contents
# 5. create the DMG
# 6. sign the DMG
# 7. submit the DMG to Apple notarization
# 8. staple the notarization ticket
# 9. verify the final notarized installer
release: clean build sign-app stage-dmg dmg sign-dmg notarize-dmg staple-dmg verify-notarization ## Build, sign, notarize, and verify the release DMG

# =========================================================
# Utility targets
# =========================================================

start-section: ## Print a section divider sized to the current terminal width.
	@printf '\n'
	@printf '%*s\n' "$$(tput cols 2>/dev/null || echo 80)" '' | tr ' ' '─'

check: check-wails ## Run prebuild checks

check-wails: ## Run Wails environment diagnostics
	@$(MAKE) start-section
	@echo "$(HEADER)Prebuild Check: Checking Wails & Dependencies...\n$(RESET)"
	@wails doctor

# =========================================================
# Build / run
# =========================================================

build: check ## Build the Wails application in production mode
	@$(MAKE) start-section
	@echo "$(HEADER)Building Wails application...\n$(RESET)"
	@if [ "$(UNAME_S)" = "Darwin" ]; then \
		wails build -platform darwin/universal -clean $(WAILS_BUILD_FLAGS) -o $(BINARY_NAME); \
	else \
		wails build -clean $(WAILS_BUILD_FLAGS) -upx -upxflags "--lzma" -o $(BINARY_NAME); \
	fi
	@$(MAKE) start-section
	@echo "Results:"
	@echo "  Build                | Success"
	@echo "  Application          | $(shell pwd)/$(APP_SOURCE)"

test: check ## Start the Wails development environment
	@$(MAKE) start-section
	@echo "$(HEADER)Starting Wails dev server for testing...\n$(RESET)"
	@wails dev

run: build ## Run the built application
	@$(MAKE) start-section
	@echo "$(HEADER)Running application...\n$(RESET)"
	@"$(APP_EXEC)"

# =========================================================
# App signing
# =========================================================

# Sign the macOS .app bundle with the Developer ID Application certificate.
# --options runtime enables Hardened Runtime, which Apple notarization requires.
# --keychain explicitly points codesign at the login keychain to avoid ambiguity.
sign-app: build ## Sign the macOS app bundle
	@$(MAKE) start-section
	@echo "$(HEADER)Signing application...\n$(RESET)"
	@codesign --deep --force --options runtime \
		--keychain ~/Library/Keychains/login.keychain-db \
		--sign "$(APPLE_SIGN_IDENTITY)" \
		"$(APP_SOURCE)"
	@echo "$(GREEN)Signed$(RESET) | $(shell pwd)/$(APP_SOURCE)"

verify-sign: sign-app ## Verify the app signature with codesign and Gatekeeper
	@$(MAKE) start-section
	@echo "$(HEADER)Verifying application signature...\n$(RESET)"
	@codesign --verify --deep --strict --verbose=2 "$(APP_SOURCE)"
	@spctl --assess --type execute --verbose "$(APP_SOURCE)"
	@echo "$(GREEN)Signature Verified$(RESET) | $(shell pwd)/$(APP_SOURCE)"

# =========================================================
# DMG staging
# =========================================================

# Prepare a folder structure for signed DMG creation:
# - copy the signed app bundle into a staging folder
# - add an /Applications symlink for drag-and-drop installation
stage-dmg: sign-app ## Stage signed DMG contents
	@$(MAKE) start-section
	@echo "$(HEADER)Staging DMG contents...\n$(RESET)"
	@rm -rf "$(DMG_DIR)"
	@mkdir -p "$(DMG_DIR)"
	@cp -R "$(APP_SOURCE)" "$(DMG_DIR)/$(APP_NAME)"
	@ln -s /Applications "$(DMG_DIR)/Applications"
	@echo "$(GREEN)Staged$(RESET) | $(shell pwd)/$(DMG_DIR)"

# Prepare a folder structure for unsigned DMG creation.
stage-dmg-unsigned: build ## Stage unsigned DMG contents
	@$(MAKE) start-section
	@echo "$(HEADER)Staging unsigned DMG contents...\n$(RESET)"
	@rm -rf "$(DMG_DIR)"
	@mkdir -p "$(DMG_DIR)"
	@cp -R "$(APP_SOURCE)" "$(DMG_DIR)/$(APP_NAME)"
	@ln -s /Applications "$(DMG_DIR)/Applications"
	@echo "$(GREEN)Staged Unsigned$(RESET) | $(shell pwd)/$(DMG_DIR)"

# =========================================================
# DMG creation
# =========================================================

dmg: stage-dmg ## Create a signed-path DMG from staged contents
	@$(MAKE) start-section
	@echo "$(HEADER)Creating DMG...\n$(RESET)"
	@rm -f "$(DMG_PATH)"
	@hdiutil create \
		-volname "$(VOL_NAME)" \
		-srcfolder "$(DMG_DIR)" \
		-ov \
		-format UDZO \
		"$(DMG_PATH)"
	@echo "$(GREEN)DMG Created$(RESET) | $(shell pwd)/$(DMG_PATH)"

dmg-unsigned: stage-dmg-unsigned ## Create unsigned DMG
	@$(MAKE) start-section
	@echo "$(HEADER)Creating unsigned DMG...\n$(RESET)"
	@rm -f "$(DMG_PATH)"
	@hdiutil create \
		-volname "$(VOL_NAME)" \
		-srcfolder "$(DMG_DIR)" \
		-ov \
		-format UDZO \
		"$(DMG_PATH)"
	@echo "$(GREEN)Unsigned DMG Created$(RESET) | $(shell pwd)/$(DMG_PATH)"

# =========================================================
# DMG signing / notarization
# =========================================================

sign-dmg: dmg ## Sign DMG container
	@$(MAKE) start-section
	@echo "$(HEADER)Signing DMG...\n$(RESET)"
	@codesign --force \
		--sign "$(APPLE_SIGN_IDENTITY)" \
		"$(DMG_PATH)"
	@echo "$(GREEN)DMG Signed$(RESET) | $(shell pwd)/$(DMG_PATH)"

notarize-dmg: sign-dmg ## Submit DMG for notarization
	@$(MAKE) start-section
	@echo "$(HEADER)Submitting DMG for notarization...\n$(RESET)"
	@xcrun notarytool submit "$(DMG_PATH)" \
		--keychain-profile "$(NOTARY_PROFILE)" \
		--wait
	@echo "$(GREEN)Notarization Submitted/Accepted$(RESET) | $(shell pwd)/$(DMG_PATH)"

staple-dmg: notarize-dmg ## Staple notarization ticket
	@$(MAKE) start-section
	@echo "$(HEADER)Stapling notarization ticket...\n$(RESET)"
	@xcrun stapler staple "$(DMG_PATH)"
	@echo "$(GREEN)Stapled$(RESET) | $(shell pwd)/$(DMG_PATH)"

verify-notarization: staple-dmg ## Verify notarized DMG
	@$(MAKE) start-section
	@echo "$(HEADER)Verifying notarized DMG...\n$(RESET)"
	@xcrun stapler validate "$(DMG_PATH)"
	@spctl -a -t open -vvv --context context:primary-signature "$(DMG_PATH)"
	@echo "$(GREEN)Notarization Verified$(RESET) | $(shell pwd)/$(DMG_PATH)"

# =========================================================
# Cleanup
# =========================================================

clean: ## Remove build artifacts
	@$(MAKE) start-section
	@echo "$(HEADER)Cleaning Build Directory...\n$(RESET)"
	@rm -rf "$(BUILD_DIR)"
	@echo "Build Directory Clean"