# Name of the compiled application binary and .app bundle.
BINARY_NAME := cdnmanager

# Root build directory and subdirectory where final build artifacts are placed.
BUILD_DIR := build
BIN_DIR := $(BUILD_DIR)/bin

# Human-facing release version used in the DMG filename.
VERSION := 2.1.0

# macOS disk image volume name shown when the DMG is mounted.
VOL_NAME := CDN Manager

# Display name of the macOS .app bundle inside the staged DMG.
APP_NAME := CDN Manager.app

# Path to the packaged Wails .app bundle generated by `wails build`.
APP_SOURCE := $(BIN_DIR)/$(BINARY_NAME).app

# Path to the actual executable binary inside the .app bundle.
APP_EXEC := $(APP_SOURCE)/Contents/MacOS/$(BINARY_NAME)

# Temporary staging directory used to assemble DMG contents before packaging.
DMG_DIR := $(BUILD_DIR)/dmg

# Final DMG filename and full path to the installer artifact.
DMG_NAME := CDN-Manager-v$(VERSION).dmg
DMG_PATH := $(BIN_DIR)/$(DMG_NAME)

# Wails/Go release build flags:
# -s -w    strip symbol/debug info to reduce binary size
# -trimpath removes local filesystem paths from the compiled binary
WAILS_BUILD_FLAGS := -ldflags "-s -w" -trimpath

# Capture host OS and architecture so the build can branch by platform.
UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)

# Apple signing/notarization configuration.
APPLE_TEAM_ID := 98PKWYG94J

# Exact Developer ID Application certificate name used by codesign.
APPLE_SIGN_IDENTITY := Developer ID Application: William Veith ($(APPLE_TEAM_ID))

# notarytool keychain profile name created with: xcrun notarytool store-credentials ...
NOTARY_PROFILE := AC_PROFILE

# Terminal color / formatting escape codes used for nicer build output.
BOLD := \033[1m
RESET := \033[0m
RED := \033[1;31m
GREEN := \033[1;32m
YELLOW := \033[1;33m
HEADER := \033[1;34m

# Mark targets as phony so make does not confuse them with files of the same name.
.PHONY: all check check-wails build sign-app verify-sign stage-dmg dmg notarize-dmg staple-dmg verify-notarization release test run clean start-section

# Default target: build the application.
all: build

# Full release pipeline:
# 1. clean old build artifacts
# 2. build the app
# 3. sign the .app bundle
# 4. stage DMG contents
# 5. create the DMG
# 6. submit the DMG to Apple notarization
# 7. staple the notarization ticket
# 8. verify the final notarized installer
release: clean build sign-app stage-dmg dmg notarize-dmg staple-dmg verify-notarization

# Print a section divider sized to the current terminal width.
start-section:
	@printf '\n'
	@printf '%*s\n' "$$(tput cols 2>/dev/null || echo 80)" '' | tr ' ' '─'

# Aggregate prebuild checks.
check: check-wails

# Run Wails environment diagnostics to confirm build dependencies are available.
check-wails:
	@$(MAKE) start-section
	@echo "$(HEADER)Prebuild Check: Checking Wails & Dependencies...\n$(RESET)"
	@wails doctor

# Build the Wails app in production mode.
build: check
	@$(MAKE) start-section
	@echo "$(HEADER)Building Wails application...\n$(RESET)"
	@if [ "$(UNAME_S)" = "Darwin" ] && [ "$(UNAME_M)" = "arm64" ]; then \
		echo "Skipping UPX compression for macOS arm64"; \
		wails build -clean $(WAILS_BUILD_FLAGS) -o $(BINARY_NAME); \
	else \
		wails build -clean $(WAILS_BUILD_FLAGS) -upx -upxflags "--lzma" -o $(BINARY_NAME); \
	fi
	@$(MAKE) start-section
	@echo "Results:"
	@echo "  Build                | Success"
	@echo "  Application          | $(shell pwd)/$(APP_SOURCE)"
	@open "$(shell pwd)/$(BIN_DIR)"

# Sign the macOS .app bundle with the Developer ID Application certificate.
# --options runtime enables Hardened Runtime, which Apple notarization requires.
# --keychain explicitly points codesign at the login keychain to avoid ambiguity.
sign-app: build
	@$(MAKE) start-section
	@echo "$(HEADER)Signing application...\n$(RESET)"
	@codesign --deep --force --options runtime \
		--keychain ~/Library/Keychains/login.keychain-db \
		--sign "$(APPLE_SIGN_IDENTITY)" \
		"$(APP_SOURCE)"
	@echo "$(GREEN)Signed$(RESET) | $(shell pwd)/$(APP_SOURCE)"

# Verify that the .app bundle was signed correctly and assess it with Gatekeeper.
verify-sign: sign-app
	@$(MAKE) start-section
	@echo "$(HEADER)Verifying application signature...\n$(RESET)"
	@codesign --verify --deep --strict --verbose=2 "$(APP_SOURCE)"
	@spctl --assess --type execute --verbose "$(APP_SOURCE)"
	@echo "$(GREEN)Signature Verified$(RESET) | $(shell pwd)/$(APP_SOURCE)"

# Prepare a folder structure for DMG creation:
# - copy the signed app bundle into a staging folder
# - add an /Applications symlink for drag-and-drop installation
stage-dmg: sign-app
	@$(MAKE) start-section
	@echo "$(HEADER)Staging DMG contents...\n$(RESET)"
	@rm -rf "$(DMG_DIR)"
	@mkdir -p "$(DMG_DIR)"
	@cp -R "$(APP_SOURCE)" "$(DMG_DIR)/$(APP_NAME)"
	@ln -s /Applications "$(DMG_DIR)/Applications"
	@echo "$(GREEN)Staged$(RESET) | $(shell pwd)/$(DMG_DIR)"

# Build a compressed read-only DMG from the staged contents.
dmg: stage-dmg
	@$(MAKE) start-section
	@echo "$(HEADER)Creating DMG...\n$(RESET)"
	@rm -f "$(DMG_PATH)"
	@hdiutil create \
		-volname "$(VOL_NAME)" \
		-srcfolder "$(DMG_DIR)" \
		-ov \
		-format UDZO \
		"$(DMG_PATH)"
	@echo "$(GREEN)DMG Created$(RESET) | $(shell pwd)/$(DMG_PATH)"
	@open "$(shell pwd)/$(BIN_DIR)"

# Upload the DMG to Apple's notarization service and wait for a result.
# The credentials are pulled from the named keychain profile created earlier.
notarize-dmg: dmg
	@$(MAKE) start-section
	@echo "$(HEADER)Submitting DMG for notarization...\n$(RESET)"
	@xcrun notarytool submit "$(DMG_PATH)" \
		--keychain-profile "$(NOTARY_PROFILE)" \
		--wait
	@echo "$(GREEN)Notarization Submitted/Accepted$(RESET) | $(shell pwd)/$(DMG_PATH)"

# Attach the notarization ticket directly to the DMG.
# This allows Gatekeeper to validate the DMG offline without re-querying Apple.
staple-dmg: notarize-dmg
	@$(MAKE) start-section
	@echo "$(HEADER)Stapling notarization ticket...\n$(RESET)"
	@xcrun stapler staple "$(DMG_PATH)"
	@echo "$(GREEN)Stapled$(RESET) | $(shell pwd)/$(DMG_PATH)"

# Confirm the stapled ticket is present and verify Gatekeeper sees the DMG as notarized.
verify-notarization: staple-dmg
	@$(MAKE) start-section
	@echo "$(HEADER)Verifying notarized DMG...\n$(RESET)"
	@xcrun stapler validate "$(DMG_PATH)"
	@spctl -a -vv "$(DMG_PATH)"
	@echo "$(GREEN)Notarization Verified$(RESET) | $(shell pwd)/$(DMG_PATH)"
	@open "$(shell pwd)/$(BIN_DIR)"

# Launch the Wails development environment for frontend/backend iteration.
test: check
	@$(MAKE) start-section
	@echo "$(HEADER)Starting Wails dev server for testing...\n$(RESET)"
	@wails dev

# Run the built executable directly from inside the packaged .app bundle.
run: build
	@$(MAKE) start-section
	@echo "$(HEADER)Running application...\n$(RESET)"
	@"$(APP_EXEC)"

# Remove all build artifacts so the next build starts clean.
clean:
	@$(MAKE) start-section
	@echo "$(HEADER)Cleaning Build Directory...\n$(RESET)"
	@rm -rf "$(BUILD_DIR)"
	@echo "Build Directory Clean"