// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteKeyValue(arg1) {
  return window['go']['session']['CloudflareSession']['DeleteKeyValue'](arg1);
}

export function DeleteKeyValues(arg1) {
  return window['go']['session']['CloudflareSession']['DeleteKeyValues'](arg1);
}

export function GetAllEntries() {
  return window['go']['session']['CloudflareSession']['GetAllEntries']();
}

export function GetAllEntriesFromKeys(arg1) {
  return window['go']['session']['CloudflareSession']['GetAllEntriesFromKeys'](arg1);
}

export function GetAllKeys() {
  return window['go']['session']['CloudflareSession']['GetAllKeys']();
}

export function GetAllValues() {
  return window['go']['session']['CloudflareSession']['GetAllValues']();
}

export function GetValue(arg1) {
  return window['go']['session']['CloudflareSession']['GetValue'](arg1);
}

export function InsertKVEntry(arg1, arg2, arg3) {
  return window['go']['session']['CloudflareSession']['InsertKVEntry'](arg1, arg2, arg3);
}

export function Size() {
  return window['go']['session']['CloudflareSession']['Size']();
}

export function WriteEntries(arg1) {
  return window['go']['session']['CloudflareSession']['WriteEntries'](arg1);
}

export function WriteEntry(arg1) {
  return window['go']['session']['CloudflareSession']['WriteEntry'](arg1);
}
