// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTable() {
  return window['go']['database']['Database']['CreateTable']();
}

export function DeleteEntries(arg1) {
  return window['go']['database']['Database']['DeleteEntries'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['database']['Database']['DeleteEntry'](arg1);
}

export function DeleteName(arg1) {
  return window['go']['database']['Database']['DeleteName'](arg1);
}

export function DeleteNames(arg1) {
  return window['go']['database']['Database']['DeleteNames'](arg1);
}

export function DropTable() {
  return window['go']['database']['Database']['DropTable']();
}

export function GetAllEntries() {
  return window['go']['database']['Database']['GetAllEntries']();
}

export function GetEntriesByValue(arg1) {
  return window['go']['database']['Database']['GetEntriesByValue'](arg1);
}

export function GetEntryByName(arg1) {
  return window['go']['database']['Database']['GetEntryByName'](arg1);
}

export function GetEntryByValue(arg1) {
  return window['go']['database']['Database']['GetEntryByValue'](arg1);
}

export function InsertEntries(arg1) {
  return window['go']['database']['Database']['InsertEntries'](arg1);
}

export function InsertEntry(arg1) {
  return window['go']['database']['Database']['InsertEntry'](arg1);
}

export function Size() {
  return window['go']['database']['Database']['Size']();
}
