// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateTable():Promise<void>;

export function DeleteEntries(arg1:Array<models.Entry>):Promise<void>;

export function DeleteEntry(arg1:models.Entry):Promise<void>;

export function DeleteName(arg1:string):Promise<void>;

export function DeleteNames(arg1:Array<string>):Promise<void>;

export function DropTable():Promise<void>;

export function GetAllEntries():Promise<Array<models.Entry>>;

export function GetEntriesByValue(arg1:string):Promise<Array<models.Entry>>;

export function GetEntryByName(arg1:string):Promise<models.Entry>;

export function GetEntryByValue(arg1:string):Promise<models.Entry>;

export function InsertEntries(arg1:Array<models.Entry>):Promise<void>;

export function InsertEntry(arg1:models.Entry):Promise<void>;

export function InsertKVEntryIntoDatabase(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Size():Promise<number>;
