// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';

export function CreateTable():Promise<void>;

export function DeleteEntries(arg1:Array<session.Entry>):Promise<void>;

export function DeleteEntry(arg1:session.Entry):Promise<void>;

export function DeleteName(arg1:string):Promise<void>;

export function DeleteNames(arg1:Array<string>):Promise<void>;

export function DropTable():Promise<void>;

export function GetAllEntries():Promise<Array<session.Entry>>;

export function GetEntriesByValue(arg1:string):Promise<Array<session.Entry>>;

export function GetEntryByName(arg1:string):Promise<session.Entry>;

export function GetEntryByValue(arg1:string):Promise<session.Entry>;

export function InsertEntries(arg1:Array<session.Entry>):Promise<void>;

export function InsertEntry(arg1:session.Entry):Promise<void>;

export function Size():Promise<number>;
